server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: auth

auth:
  public-urls: /api/v1/auth/login,/api/v1/auth/signup

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:28080}
  realm: ${KEYCLOAK_REALM:cloudstorage-app}
  resource: ${KEYCLOAK_RESOURCE:cloudstorage-app}
  client: ${KEYCLOAK_CLIENT:cloudstorage-app}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET:BoY28VpJrVNxh3Qzc2x7hx4q5t3J0wFa}


logging:
  level:
    org.springframework: DEBUG

